### PR TITLE
Add a shortcut method to get grpc reply

### PR DESCRIPTION
**Pull request by liuchong**
Motivation:

In many usage cases we will call end and last, give a default shortcut method for this should be convenient I think 👀 

Please review when you have time @vietj @tsegismont , thanks!

### CODE REVIEW

**Comment by vietj** [comment]
I like the idea but I think it is too narrow and specific, I created a PR following your idea https://github.com/eclipse-vertx/vertx-grpc/pull/38, please have a look

**Comment by liuchong** [comment]
I've reviewed your PR and it looks nice!
Also maybe this `last` is still somewhat useful in some certain use cases, as a `shortcut`, how do you think? 🤔

**Comment by vietj** [comment]
I think that's too narrow to be here

**Comment by liuchong** [comment]
ok

**Pull request closed without merging**
