### PR TITLE
Fixed IndexOutOfBoundsException in GrpcMethodCall.serviceName()

### PR DESCRIPTION
**Pull request by SG-O**
This should fix the issue https://github.com/eclipse-vertx/vertx-grpc/issues/56

### CODE REVIEW

**Comment by vietj** [comment]
can you add a test @SG-O ?

**Comment by SG-O** [comment]
I added test for the whole GrpcMethodCall class. 

Implementing these revealed that the output of the fullyQualifiedName() method in ServiceNameImpl wasn't formatted well for service names without dots. I fixed this corner case so it now outputs "MyService" instead of ".MyService".

**Comment by SG-O** [comment]
I found another two minor bugs. 

In the implementation of GrpcMethodCall.methodName() the name would have a leading slash (e.g. /Method1) which is not compatible with ServiceName.pathOf(String method). I changed the output to not include this slash.

The ServiceName.packageName() and .pathOf() methods did not handle fully qualified names without a package name correctly. I fixed this and added a lot more tests for the whole ServiceName class.

Both GrpcMethodCall and ServiceName now have full coverage from their respective tests.

This should be ready to  merge.

**Comment by vietj** [comment]
can you resolved the conflict due to merging https://github.com/eclipse-vertx/vertx-grpc/pull/59 ? @SG-O

**Comment by SG-O** [comment]
On it

**Comment by vietj** [comment]
can you provide a backport to 4.x branch @SG-O ?

**Pull request merged**
